### ISSUE TITLE
Hacer un listado de 1 producto por línea

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/listadelacompraJS#2]
Ahora mismo en los dos casos están listados los elementos a cholón. Queremos que haya una lista principal donde haya un listado de productos y cada item puede ser una cadena con los datos o una lista con los datos de cada item.

Dudas a mi y cada una en su rama :)

**Comment by oneeyedman** [comment]
Ahora mismo el listado es un ul con todos los datos, uno detrás de otro. Necesitamos no solo verlo diferente (agrupado) en el navegador sino que igual tiene que ser un solo listado con los datos de cada item en un `<li>` o un listado con una lista de datos en cada `<li>`. 

Como en esta imagen: https://www.dropbox.com/s/ozq0fktemmqkwjl/listados.png?dl=0

**Comment by MoniAguado** [comment]
Hecho! Mira a ver si esto lo que pedías :)

**Comment by MamenRC** [comment]
Hecho! Cuando puedas me dices si era esto.

**Comment by oneeyedman** [comment]
Buen trabajo a las dos! Por aquí iban los tiros de lo que se pedía en el ejercicio inicial.

@MoniAguado ten cuidado con tu solución porque no debes meter un `<p>` dentro de otro `<p>`. De echo el navegador no te va a dejar y va a solucionarlo como pueda, en este caso no descuadra nada pero en otros sí que lo hará.
