### ISSUE TITLE
Pintar el listado con una función

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/listadelacompraJS#3]
Aunque el listado se pinte al cargar la página queremos usar una función para ello, sí?

**Comment by MamenRC** [comment]
Ya esta metido el listado en una función. ;)

**Comment by oneeyedman** [comment]
@MamenRC, no lo veo metido en una función, ahora mismo el listado se pinta al cargar la página sin llamar a ninguna función. Posiblemente esté en el código comentado.

**Comment by oneeyedman** [comment]
Excelente! Buen trabajo a las dos, @MamenRC y @MoniAguado. Es interesante englobar pequeñas tareas en funciones  y usarlas cuando nos haga falta. Nos ayuda a tener un código más ordenado y modular.
