### ISSUE TITLE
Ahora vamos a pasar el código a ES2015 (ES6) y aprovechar para limpiarlo un poco

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/listadelacompraJS#4]
#Tareas:
- [x] Ordenarlo un poco, si procede: definición de variables arriba, luego funciones y luego el resto del código.
- [x] Indentado correcto.
- [x] Eliminar código comentado (dejar solo comentarios como `//CALCULAR EL TOTAL`
- [x] Pasar a ES6: let/const, concatenados, bucles for (si hemos usado `map` lo reharemos con un for de los nuevos) y funciones flecha.

**Comment by oneeyedman** [comment]
Muy buen trabajo, @MamenRC! 
Tienes un par de errorcillos: 
1) en la línea 41 hay un `<li>` sin cerrar. Para esto igual te ayuda esto que se puede hacer con las concatenados de ES6, podríamos escribir esto:
```
menuLi += `
	<li class="menu">
		<ul class="listDetails">
			<li class="name"> ${list.product}</li>
			<li class="menu">Precio: ${list.price} €</li>
			<li class="menu">Cantidad: ${list.quantity}</li>
			<li class="menu">Total: ${list.price} * ${list.quantity} €
		</ul>
	</li>
	`
```
Usando este sistema es más fácil identificar etiquetas perdidas ;)

2) en la línea 51 la operación no genera el resultado esperado porque  no estás multiplicando realmente: estás escribiendo el precio, un asterisco y el precio de nuevo, y como es una cadena, se va añadiendo todo el rato. Y si sigues pulsando el botón de calcular precio te va aumentando.
Para solucionarlo habría que hacer estas cosas:
1. La variable total tendría que ir dentro de la función ya que no se le da un uso global, esto, además, evitaría que se vayan acumulando totales si pulsas muchas veces el botón de calcular total.
2. El cálculo del total debería ser algo tipo `total += prices.quantity * prices.price; ` ya que queremos, de cada item, calcular el precio unitario por la cantidad de items que vamos a comprar.

Le echas un ojo cuando puedas?

**Comment by MamenRC** [comment]
Carlos,

Esta línea <li class="menu">Total: ${list.price} * ${list.quantity} €</li>
Sigue saliendo la multiplicación pero no el resultado, que es lo que quiero que salga.

**Comment by oneeyedman** [comment]
Ya veo, en este caso tendás que poner la operación entera entre llaves: `Total: ${list.price * list.quantity} €`

**Comment by oneeyedman** [comment]
Estupendo, @MamenRC. Damos este issue por cerrado y en un rato pongo otro :)

Buen trabajo!
