### ISSUE TITLE
Ahora vamos a pasar el código a ES2015 (ES6) y aprovechar para limpiarlo un poco

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/listadelacompraJS#5]
Tareas:
- [x] Ordenarlo un poco, si procede: definición de variables arriba, luego funciones y luego el resto del código.
- [x] Indentado correcto.
- [x] Eliminar código comentado (dejar solo comentarios como `//CALCULAR EL TOTAL`
- [x] Pasar a ES6: let/const, concatenados, bucles for (si hemos usado `map` lo reharemos con un for de los nuevos) y funciones flecha.

**Comment by MoniAguado** [comment]
Hola Carlos, ya he subido estos cambios. Ya me darás tu feedback y nuevas tareas :)

**Comment by oneeyedman** [comment]
Está genial, @MoniAguado! 

Quizás la variable `list` la definiría dentro de la función en este caso en lugar de hacerla variable global.

Pero está bien, lo cierro y pongo el siguiente!
