### ISSUE TITLE
Vamos a crear el entorno para darle un poco de interactividad a nuestra lista de la compra

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/listadelacompraJS#6]
Para el siguiente truco vamos a necesitar dos cosas:
- [x] Que nuestra lista de la compra se encuentre dentro de una etiqueta formulario
- [x] Que cada item de la lista tenga, antes del nombre, un checkbox.

Sí?

**Comment by MamenRC** [comment]
Ya lo tienes!!!
