### ISSUE TITLE
Vamos a crear el entorno para darle un poco de interactividad a nuestra lista de la compra

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/listadelacompraJS#7]
Para el siguiente truco vamos a necesitar dos cosas:
- [x] Que nuestra lista de la compra se encuentre dentro de una etiqueta formulario
- [x] Que cada item de la lista tenga, antes del nombre, un checkbox.

Esto va a ser para preparar que el botón de calcular precio solo sume los items que hemos marcado, por ahora solo vamos a preparar el terreno.

Sí?

**Comment by oneeyedman** [comment]
En principio está bien aunque mejor no te adelantes porque lo del input ni lo tenía en mente.

Antes de cerrarlo hay que hacer algunas cosas:
- [ ] Todos los inputs/textareas/selects que pongamos tendrán estos dos atributos: id y name (salvo que nos digan otra cosa, o sean radiobuttons, el id y el name serán el mismo valor y tendrá que ser único, no puede estar repetido en otro elemento de la página).
- [ ] Cuando pongamos un campo debería tener un label, en el caso de los checkbox es super normal que el label contenga el input y el texto de la etiqueta, en este caso tendría un aspecto como:
```html
<label for="item1">
  <input name="item1" id="item1" type="checkbox">
  Producto: Cereales con chocolate
</label>
```

**Comment by MoniAguado** [comment]
Hecho!
